name = "APT"
author = "Apsu"
link = "github.com/apsu/apt"
year = 2021

[formats.standard]
matrix = [["w", "g", "d", "f", "b", "q", "l", "u", "o", "y"],
["r", "s", "t", "h", "k", "j", "n", "e", "a", "i", ";"],
["x", "c", "m", "p", "v", "z", ",", ".", "'", "/"]]

map = {}
home_row = 1
