name = "APTx"
author = "Apsu"
link = "github.com/apsu/aptx"
year = 2021

[formats.standard]
matrix = [["q", "c", "d", "w", "x", "z", "p", "o", "u", ";"],
["r", "s", "t", "n", "v", "y", "h", "e", "i", "a"],
["l", "g", "b", "m", "j", "k", "f", "'", ",", "."]]

map = {}
home_row = 1
