name = "ARTS"
author = "ClemenPine"
link = ""
year = 2021

[formats.standard]
matrix = [["q", "l", "d", "y", "g", "j", "m", "o", "u", ";"],
["a", "r", "t", "s", "c", "p", "n", "e", "i", "h", "/"],
["z", "x", "k", "w", "v", "b", "f", "'", ",", "."]]

map = {}
home_row = 1
