name = "BEAKL-49"
author = "Mati the Key"
link = ""
year = 0

[formats.standard]
matrix = [["z", "y", "o", "u", "k", "g", "m", "l", "p", "j", ";", "="],
["h", "i", "e", "a", "f", "d", "s", "t", "n", "r", "-", "\\"],
["/", ".", ",", "'", "x", "w", "c", "v", "b", "q"]]

map = {}
home_row = 1
