name = "BEAKL-19-BIS"
author = "Xay Voong"
link = ""
year = 2020

[formats.standard]
matrix = [["q", "y", "o", "u", "z", "w", "d", "n", "c", "k"],
["h", "i", "e", "a", ",", "g", "t", "r", "s", "p"],
["j", "'", "/", ".", "x", "v", "m", "l", "f", "b"]]

map = {}
home_row = 1
