name = "BEAKL-19"
author = "Xay Voong"
link = ""
year = 2020

[formats.standard]
matrix = [["q", ".", "o", "u", "j", "w", "d", "n", "m", ","],
["h", "a", "e", "i", "k", "g", "s", "r", "t", "p"],
["z", "'", "/", "y", "x", "b", "c", "l", "f", "v"]]

map = {}
home_row = 1
