name = "BEAKL-15"
author = "Xay Voong"
link = ""
year = 0

[formats.standard]
matrix = [["q", "h", "o", "u", "x", "g", "c", "r", "f", "z"],
["y", "i", "e", "a", ".", "d", "s", "t", "n", "b"],
["j", "/", ",", "k", "'", "w", "m", "l", "p", "v"]]

map = {}
home_row = 1
