name = "Capewell-Dvorak"
author = "Michael Capewell"
link = ""
year = 2005

[formats.standard]
matrix = [["'", ",", ".", "p", "y", "q", "f", "g", "r", "k"],
["o", "a", "e", "i", "u", "d", "h", "t", "n", "s"],
["z", "x", "c", "v", "j", "l", "m", "w", "b", ";"]]

map = {}
home_row = 1
