name = "Colemak"
author = "Shai Coleman"
link = "colemak.com"
year = 2006

[formats.standard]
matrix = [["q", "w", "f", "p", "g", "j", "l", "u", "y", ";"],
["a", "r", "s", "t", "d", "h", "n", "e", "i", "o", "'"],
["z", "x", "c", "v", "b", "k", "m", ",", ".", "/"]]

map = {}
home_row = 1
