name = "Colemak Qi"
author = "nyfee"
link = ""
year = 2021

[formats.standard]
matrix = [["q", "l", "w", "m", "k", "j", "f", "u", "y", "'"],
["a", "r", "s", "t", "g", "p", "n", "e", "i", "o", ";"],
["z", "x", "c", "d", "v", "b", "h", ",", ".", "/"]]

map = {}
home_row = 1
