name = "Colman"
author = "Unknown"
link = ""
year = 2015

[formats.standard]
matrix = [["q", "l", "r", "w", "b", "j", "m", "u", "y", ";"],
["a", "n", "h", "s", "f", "p", "t", "e", "i", "o", "'"],
["z", "x", "v", "c", "k", "g", "d", ",", ".", "/"]]

map = {}
home_row = 1
