name = "CTGAP 3.0"
author = "Colby Chai"
link = ""
year = 2021

[formats.standard]
matrix = [["v", "p", "l", "c", "f", "k", "u", "o", "y", "j"],
["r", "n", "t", "s", "d", "'", "a", "e", "i", "h"],
["z", "b", "m", "g", "w", "x", ",", ".", ";", "q"]]

map = {}
home_row = 1
