name = "Dvarf"
author = "Oxey"
link = ""
year = 2021

[formats.standard]
matrix = [["'", "u", "o", "w", "p", "q", "v", "d", "r", "f"],
["a", "i", "e", "y", "g", "l", "h", "t", "n", "s"],
[",", ".", ";", "c", "j", "k", "m", "b", "x", "z"]]

map = {}
home_row = 1