name = "Dvormax"
author = "PieterGen"
link = ""
year = 0

[formats.standard]
matrix = [["k", "y", "u", ".", "?", "z", "l", "m", "d", "p", "v"],
["r", "i", "e", "a", "o", "h", "n", "s", "t", "c", "w"],
["x", ")", "'", ",", "(", "j", "q", "f", "g", "b"]]

map = {}
home_row = 1
