name = "Dwarf"
author = "StronglyTyped"
link = ""
year = 2021

[formats.standard]
matrix = [["f", "l", "h", "d", "v", "z", "g", "o", "u", "."],
["s", "r", "n", "t", "m", "p", "y", "e", "i", "a"],
["x", "j", "b", "k", "q", "c", "w", "'", ",", ";"]]

map = {}
home_row = 1
