name = "Hands Up"
author = "Oxey"
link = ""
year = 2022

[formats.standard]
matrix = [["f", "y", "o", "u", ",", "k", "w", "c", "l", "p"],
["h", "i", "e", "a", ".", "d", "t", "s", "r", "n"],
["b", "j", "'", "z", ";", "v", "m", "g", "x", "q"]]

map = {}
home_row = 1
