name = "Hyperroll"
author = "Semi"
link = ""
year = 2021

[formats.standard]
matrix = [["p", "c", "l", "m", "v", "x", "u", "o", "y", "f"],
["n", "s", "r", "t", "d", ".", "a", "e", "i", "h"],
["b", "g", "'", "w", "z", "/", ",", "q", "j", "k"]]

map = {}
home_row = 1