name = "ISRT"
author = "NotGate"
link = "notgate.github.io/layout"
year = 2021

[formats.standard]
matrix = [["y", "c", "l", "m", "k", "z", "f", "u", ",", "'"],
["i", "s", "r", "t", "g", "p", "n", "e", "a", "o", ";"],
["q", "v", "w", "d", "j", "b", "h", "/", ".", "x"]]

map = {}
home_row = 1
