name = "Klausler"
author = "Peter Klausler"
link = ""
year = 0

[formats.standard]
matrix = [["k", ",", "u", "y", "p", "w", "l", "m", "f", "c"],
["o", "a", "e", "i", "d", "r", "n", "t", "h", "s"],
["q", ".", "'", ";", "z", "x", "v", "g", "b", "j"]]

map = {}
home_row = 1
