name = "Minimak-12"
author = "Ted Lilley"
link = "minimak.org"
year = 2012

[formats.standard]
matrix = [["q", "w", "d", "f", "k", "y", "u", "i", "l", ";"],
["a", "s", "t", "r", "g", "h", "n", "e", "o", "p", "'"],
["z", "x", "c", "v", "b", "j", "m", ",", ".", "/"]]

map = {}
home_row = 1
