name = "Morgenstern"
author = "Kharlamov and Sagittarius"
link = ""
year = 2022

[formats.standard]
matrix = [["j", "c", "a", "ö", "y", "ß", "k", "l", "f", "p", "."],
["t", "n", "e", "i", "o", "g", "h", "r", "s", "w", "b"],
["q", "m", "ä", "u", "ü", "v", "d", "x", "z", ","]]

map = {}
home_row = 1
