name = "Niro"
author = "Kennet Chaz"
link = ""
year = 0

[formats.standard]
matrix = [["q", "w", "u", "d", "p", "j", "f", "y", "l", ";"],
["a", "s", "e", "t", "g", "h", "n", "i", "r", "o", "'"],
["z", "x", "c", "v", "b", "k", "m", ",", ".", "/"]]

map = {}
home_row = 1
