name = "Oneproduct"
author = "oneproduct"
link = ""
year = 0

[formats.standard]
matrix = [["p", "l", "d", "w", "g", "j", "x", "o", "y", "q"],
["n", "r", "s", "t", "m", "u", "a", "e", "i", "h"],
["z", "c", "f", "v", "b", ",", ".", "?", ";", "k"]]

map = {}
home_row = 1
