name = "Pine"
author = "ClemenPine"
link = ""
year = 2021

[formats.standard]
matrix = [["y", "l", "r", "d", "w", "j", "m", "o", "u", ","],
["c", "s", "n", "t", "g", "p", "h", "a", "e", "i"],
["x", "z", "q", "v", "k", "b", "f", "'", "/", "."]]

map = {}
home_row = 1
