name = "QGMLWY"
author = "Martin Krzywinski"
link = ""
year = 2005

[formats.standard]
matrix = [["q", "g", "m", "l", "w", "y", "f", "u", "b", ";"],
["d", "s", "t", "n", "r", "i", "a", "e", "o", "h", "'"],
["z", "x", "c", "v", "j", "k", "p", ",", ".", "/"]]

map = {}
home_row = 1
