name = "Real"
author = "StronglyTyped"
link = ""
year = 2021

[formats.standard]
matrix = [["y", "l", "u", "o", ".", "z", "f", "h", "c", "w", "/", "="],
["i", "r", "e", "a", ",", "d", "t", "n", "s", "m", "-"],
[";", "j", "'", "q", "x", "p", "k", "b", "g", "v"]]

map = {}
home_row = 1
