name = "Semimak JQ"
author = "semi"
link = "semilin.github.io/semimak"
year = 2021

[formats.standard]
matrix = [["f", "l", "h", "v", "z", "'", "w", "u", "o", "y"],
["s", "r", "n", "t", "k", "c", "d", "e", "a", "i", ";"],
["x", "j", "b", "m", "q", "p", "g", ",", ".", "/"]]

map = {}
home_row = 1
