name = "SIND"
author = "NotGate"
link = "notgate.github.io/layout/experimental"
year = 2021

[formats.standard]
matrix = [["y", ",", "h", "w", "f", "q", "k", "o", "u", "x"],
["s", "i", "n", "d", "c", "v", "t", "a", "e", "r"],
["j", ".", "l", "p", "b", "g", "m", ";", "/", "z"]]

map = {}
home_row = 1
