name = "Sertain"
author = "Smudge"
link = ""
year = 2021

[formats.standard]
matrix = [["x", "l", "d", "k", "v", "z", "w", "o", "u", ";"],
["s", "r", "t", "n", "f", "g", "y", "e", "i", "a", "/"],
["q", "j", "m", "h", "b", "p", "c", "'", ",", "."]]

map = {}
home_row = 1
