name = "TAHAN"
author = "hughlaurie1959"
link = ""
year = 2021

[formats.standard]
matrix = [["t", "a", "h", "z", "y", "x", "u", "i", "o", "p"],
["q", "v", "g", "r", "s", "n", "k", "b", "l", "w"],
["m", "f", "e", "c", "d", "j", "'", ";", "/", "-"]]

map = {}
home_row = 1