name = "trendy"
author = "stronglytyped"
link = ""
year = 2021

[formats.standard]
matrix = [["k", "l", "h", "w", "z", "j", "f", "o", "u", ","],
["t", "r", "n", "d", "c", "y", "s", "a", "e", "i"],
["q", "x", "m", "p", "b", "g", "v", ".", "'", ";"]]

map = {}
home_row = 1
