name = "Turducken"
author = "Renato"
link = ""
year = 2021

[formats.standard]
matrix = [["y", "l", "u", "v", "k", "j", "w", "o", "b", ","],
["i", "r", "e", "t", "g", "f", "s", "a", "n", "h"],
["z", "x", ";", "d", "p", "m", "c", "q", ".", "/"]]

map = {}
home_row = 1
