name = "Vitrimak"
author = "semi"
link = ""
year = 2021

[formats.standard]
matrix = [["t", "k", "v", "u", "m", "i", "a", "j", "b", "r"],
["w", "x", "/", "f", "p", "d", "g", "q", ",", "s"],
["h", ".", "'", "c", "o", "l", "n", "z", "y", "e"]]

map = {}
home_row = 1
